[package]
name = "fifo_native"
publish = false
version = "0.1.0"
authors = []
edition = "2018"

[lib]
name = "fifo_native"
path = "src/lib.rs"
crate-type = ["dylib"]

[dependencies]
lazy_static = "1.0"
nix = "0.15.0"
rustler = "0.21.0"
